# Generated by Django 5.2 on 2025-12-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('category', models.CharField(choices=[('utilities', 'Contas de Serviços (Água/Luz/Internet)'), ('supplies', 'Suprimentos'), ('maintenance', 'Manutenção'), ('staff', 'Salários e Benefícios'), ('marketing', 'Marketing e Publicidade'), ('taxes', 'Impostos e Taxas'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Categoria')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('payment_date', models.DateField(verbose_name='Data de Pagamento')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de Pagamento')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Comprovante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtraIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('received_date', models.DateField(verbose_name='Data de Recebimento')),
                ('method', models.CharField(max_length=50, verbose_name='Método de Recebimento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Receita Avulsa',
                'verbose_name_plural': 'Receitas Avulsas',
            },
        ),
        migrations.CreateModel(
            name='LedgerAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(blank=True, max_length=30, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_financeiros', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
