# Generated by Django 5.2 on 2025-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('category', models.CharField(choices=[('utilities', 'Contas de Serviços (Água/Luz/Internet)'), ('supplies', 'Suprimentos'), ('maintenance', 'Manutenção'), ('staff', 'Salários e Benefícios'), ('marketing', 'Marketing e Publicidade'), ('taxes', 'Impostos e Taxas'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Categoria')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('payment_date', models.DateField(verbose_name='Data de Pagamento')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de Pagamento')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Comprovante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-payment_date'],
            },
        ),
    ]
