# Generated by Django 5.2 on 2025-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('received_date', models.DateField(verbose_name='Data de Recebimento')),
                ('method', models.CharField(max_length=50, verbose_name='Método de Recebimento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Receita Avulsa',
                'verbose_name_plural': 'Receitas Avulsas',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
    ]
