# Generated by Django 5.2 on 2025-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='clean', max_length=20),
        ),
    ]
