# Generated by Django 5.2.6 on 2025-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Diária Padrão'),
        ),
    ]
