name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar uv
        run: pip install uv
      - name: Instalar dependências
        run: uv pip install -r requirements.txt
      - name: Black
        run: black --check --line-length 88 .
      - name: isort
        run: isort --profile=black --check .
      - name: flake8
        run: flake8 .

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar uv
        run: pip install uv
      - name: Instalar dependências
        run: uv pip install -r requirements.txt
      - name: Rodar testes e cobertura
        run: pytest -q

  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar uv
        run: pip install uv
      - name: Instalar dependências
        run: uv pip install -r requirements.txt
      - name: Instalar safety
        run: uv pip install safety
      - name: Checar vulnerabilidades
        run: safety check -r requirements.txt
